const state = () =>({
    BoardSpaces:[
        {id:0, spaceType:'go', spaceClass:'Corner Go', spaceName:'GO', cost:0, spaceText:'Collect $200 Salary As You Pass'},
        {id:1, spaceType:'property', spaceClass:'Property', spaceName:'Mediterranean Avenue', colorGroup:'blueviolet', cost:60},
        {id:2, spaceType:'community', spaceClass:'Community', spaceName:'Community Chest', cost:0},
        {id:3, spaceType:'property', spaceClass:'Property', spaceName:'Baltic Avenue', colorGroup:'blueviolet', cost:60},
        {id:4, spaceType:'incomeTax', spaceClass:'Tax', spaceName:'Income Tax', cost:200},
        {id:5, spaceType:'railroad', spaceClass:'Railroad', spaceName:'Reading Railroad', cost:200},
        {id:6, spaceType:'property', spaceClass:'Property', spaceName:'Oriental Avenue', colorGroup:'lightBlue', cost:100},
        {id:7, spaceType:'chance', spaceClass:'Chance', spaceName:'Chance', colorGroup:'magenta', cost:0},
        {id:8, spaceType:'property', spaceClass:'Property', spaceName:'Vermont Avenue', colorGroup:'lightBlue', cost:100},
        {id:9, spaceType:'property', spaceClass:'Property', spaceName:'Connecticut Avenue', colorGroup:'lightBlue', cost:120},
        {id:10, spaceType:'jail', spaceClass:'Corner InJail', spaceName:'Just Visiting', cost:0, spaceText:'Just Visiting'},
        {id:11, spaceType:'property', spaceClass:'Property', spaceName:'St. Charles Place', colorGroup:'magenta', cost:140},
        {id:12, spaceType:'electric', spaceClass:'Utility', spaceName:'Electric Company', cost:150},
        {id:13, spaceType:'property', spaceClass:'Property', spaceName:'States Avenue', colorGroup:'magenta', cost:140},
        {id:14, spaceType:'property', spaceClass:'Property', spaceName:'Virginia Avenue', colorGroup:'magenta', cost:160},
        {id:15, spaceType:'railroad', spaceClass:'Railroad', spaceName:'Pennsylvania Railroad', cost:200},
        {id:16, spaceType:'property', spaceClass:'Property', spaceName:'St James Place', colorGroup:'gold', cost:180},
        {id:17, spaceType:'community', spaceClass:'Community', spaceName:'Community Chest', cost:0},
        {id:18, spaceType:'property', spaceClass:'Property', spaceName:'Tennessee Avenue', colorGroup:'gold', cost:180},
        {id:19, spaceType:'property', spaceClass:'Property', spaceName:'New York Avenue', colorGroup:'gold', cost:200},
        {id:20, spaceType:'parking', spaceClass:'Corner FreeParking',spaceName:'Free Parking', cost:0},
        {id:21, spaceType:'property', spaceClass:'Property', spaceName:'Kentucky Avenue', colorGroup:'red', cost:220},
        {id:22, spaceType:'chance', spaceClass:'Chance', spaceName:'Chance', colorGroup:'darkblue', cost:0},
        {id:23, spaceType:'property', spaceClass:'Property', spaceName:'Indiana Avenue', colorGroup:'red', cost:220},
        {id:24, spaceType:'property', spaceClass:'Property', spaceName:'Illinois Avenue', colorGroup:'red', cost:240},
        {id:25, spaceType:'railroad', spaceClass:'Railroad', spaceName:'B & O Railroad', cost:200},
        {id:26, spaceType:'property', spaceClass:'Property', spaceName:'Atlantic Avenue', colorGroup:'yellow', cost:260},
        {id:27, spaceType:'property', spaceClass:'Property', spaceName:'Ventnor Avenue', colorGroup:'yellow', cost:260},
        {id:28, spaceType:'waterworks', spaceClass:'Utility', spaceName:'Water Works', cost:150},
        {id:29, spaceType:'property', spaceClass:'Property', spaceName:'Marvin Gardens', colorGroup:'yellow', cost:280},
        {id:30, spaceType:'gojail', spaceClass:'Corner GoJail', spaceName:'GO TO JAIL', cost:0},
        {id:31, spaceType:'property', spaceClass:'Property', spaceName:'Pacific Avenue', colorGroup:'green', cost:300},
        {id:32, spaceType:'property', spaceClass:'Property', spaceName:'North Carolina Avenue', colorGroup:'green', cost:300},
        {id:33, spaceType:'community', spaceClass:'Community', spaceName:'Community Chest', cost:0},
        {id:34, spaceType:'property', spaceClass:'Property', spaceName:'Pennsylvania Avenue', colorGroup:'green', cost:320},
        {id:35, spaceType:'railroad', spaceClass:'Railroad', spaceName:'Short Line', cost:200},
        {id:36, spaceType:'chance', spaceClass:'Chance', spaceName:'Chance', colorGroup:'pink', cost:0},
        {id:37, spaceType:'property', spaceClass:'Property', spaceName:'Park Place', colorGroup:'darkblue', cost:350},
        {id:38, spaceType:'luxtax', spaceClass:'Tax', spaceName:'Luxury Tax', cost:75},
        {id:39, spaceType:'property', spaceClass:'Property', spaceName:'Boardwalk', colorGroup:'darkblue', cost:400},
    ],
    Properties:[
        {
            boardId:1,
            propertyType: 'BlueViolet-Group',
            propertyName: 'Mediterranean Avenue',
            baseRent:2,
            oneHouseRent:10,
            twoHouseRent:30,
            threeHouseRent:90,
            fourHouseRent:160,
            hotelRent:250,
            mortgageValue:30,
            houseCost:50,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:3,
            propertyType: 'BlueViolet-Group',
            propertyName: 'Baltic Avenue',
            baseRent:4,
            oneHouseRent:20,
            twoHouseRent:60,
            threeHouseRent:180,
            fourHouseRent:320,
            hotelRent:450,
            mortgageValue:30,
            houseCost:50,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:6,
            propertyType: 'LtBlue-Group',
            propertyName: 'Oriental Avenue',
            baseRent:6,
            oneHouseRent:30,
            twoHouseRent:90,
            threeHouseRent:270,
            fourHouseRent:400,
            hotelRent:550,
            mortgageValue:50,
            houseCost:50,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:8,
            propertyType: 'LtBlue-Group',
            propertyName: 'Vermont Avenue',
            baseRent:6,
            oneHouseRent:30,
            twoHouseRent:90,
            threeHouseRent:270,
            fourHouseRent:400,
            hotelRent:550,
            mortgageValue:50,
            houseCost:50,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:9,
            propertyType: 'LtBlue-Group',
            propertyName: 'Connecticut Avenue',
            baseRent:8,
            oneHouseRent:40,
            twoHouseRent:100,
            threeHouseRent:300,
            fourHouseRent:450,
            hotelRent:450,
            mortgageValue:60,
            houseCost:50,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:11,
            propertyType: 'Magenta-Group',
            propertyName: 'St Charles Place',
            baseRent:10,
            oneHouseRent:50,
            twoHouseRent:150,
            threeHouseRent:450,
            fourHouseRent:625,
            hotelRent:750,
            mortgageValue:70,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:13,
            propertyType: 'Magenta-Group',
            propertyName: 'States Avenue',
            baseRent:10,
            oneHouseRent:50,
            twoHouseRent:150,
            threeHouseRent:450,
            fourHouseRent:625,
            hotelRent:750,
            mortgageValue:70,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:14,
            propertyType: 'Magenta-Group',
            propertyName: 'Virginia Avenue',
            baseRent:12,
            oneHouseRent:60,
            twoHouseRent:150,
            threeHouseRent:450,
            fourHouseRent:625,
            hotelRent:750,
            mortgageValue:70,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:16,
            propertyType: 'Gold-Group',
            propertyName: 'St James Place',
            baseRent:14,
            oneHouseRent:70,
            twoHouseRent:200,
            threeHouseRent:550,
            fourHouseRent:750,
            hotelRent:950,
            mortgageValue:90,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:18,
            propertyType: 'Gold-Group',
            propertyName: 'Tennessee Avenue',
            baseRent:14,
            oneHouseRent:70,
            twoHouseRent:200,
            threeHouseRent:550,
            fourHouseRent:750,
            hotelRent:950,
            mortgageValue:90,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:19,
            propertyType: 'Gold-Group',
            propertyName: 'New York Avenue',
            baseRent:16,
            oneHouseRent:80,
            twoHouseRent:220,
            threeHouseRent:600,
            fourHouseRent:800,
            hotelRent:100,
            mortgageValue:100,
            houseCost:100,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:21,
            propertyType: 'Red-Group',
            propertyName: 'Kentucky Avenue',
            baseRent:18,
            oneHouseRent:90,
            twoHouseRent:250,
            threeHouseRent:700,
            fourHouseRent:875,
            hotelRent:1050,
            mortgageValue:110,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:23,
            propertyType: 'Red-Group',
            propertyName: 'Indiana Avenue',
            baseRent:18,
            oneHouseRent:90,
            twoHouseRent:250,
            threeHouseRent:700,
            fourHouseRent:875,
            hotelRent:1050,
            mortgageValue:110,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:24,
            propertyType: 'Red-Group',
            propertyName: 'Illinois Avenue',
            baseRent:20,
            oneHouseRent:100,
            twoHouseRent:300,
            threeHouseRent:750,
            fourHouseRent:925,
            hotelRent:1100,
            mortgageValue:120,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:26,
            propertyType: 'Yellow-Group',
            propertyName: 'Atlantic Avenue',
            baseRent:22,
            oneHouseRent:110,
            twoHouseRent:330,
            threeHouseRent:800,
            fourHouseRent:975,
            hotelRent:1150,
            mortgageValue:130,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:27,
            propertyType: 'Yellow-Group',
            propertyName: 'Ventnor Avenue',
            baseRent:22,
            oneHouseRent:110,
            twoHouseRent:330,
            threeHouseRent:800,
            fourHouseRent:975,
            hotelRent:1150,
            mortgageValue:130,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:29,
            propertyType: 'Yellow-Group',
            propertyName: 'Marvin Gardens',
            baseRent:24,
            oneHouseRent:120,
            twoHouseRent:360,
            threeHouseRent:850,
            fourHouseRent:1025,
            hotelRent:1200,
            mortgageValue:140,
            houseCost:150,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:31,
            propertyType: 'Green-Group',
            propertyName: 'Pacific Avenue',
            baseRent:26,
            oneHouseRent:130,
            twoHouseRent:390,
            threeHouseRent:900,
            fourHouseRent:1100,
            hotelRent:1275,
            mortgageValue:150,
            houseCost:200,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:32,
            propertyType: 'Green-Group',
            propertyName: 'North Carolina Avenue',
            baseRent:26,
            oneHouseRent:130,
            twoHouseRent:390,
            threeHouseRent:900,
            fourHouseRent:1100,
            hotelRent:1275,
            mortgageValue:150,
            houseCost:200,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:34,
            propertyType: 'Green-Group',
            propertyName: 'Pennsylvania Avenue',
            baseRent:28,
            oneHouseRent:150,
            twoHouseRent:450,
            threeHouseRent:1000,
            fourHouseRent:1200,
            hotelRent:1400,
            mortgageValue:160,
            houseCost:200,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:37,
            propertyType: 'Blue-Group',
            propertyName: 'Park Place',
            baseRent: 35,
            oneHouseRent:175,
            twoHouseRent:500,
            threeHouseRent:1100,
            fourHouseRent:1300,
            hotelRent:1500,
            mortgageValue:175,
            houseCost:200,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:39,
            propertyType: 'Blue-Group',
            propertyName: 'Boardwalk',
            baseRent: 50,
            oneHouseRent:200,
            twoHouseRent:600,
            threeHouseRent:1400,
            fourHouseRent:1700,
            hotelRent:2000,
            mortgageValue:200,
            houseCost:200,
            monopoly:false,
            houses:0,
            owner:0
        },
        {
            boardId:12,
            propertyType: 'Utility',
            propertyName: 'Electric Company',
            propertyImage:'electric',
            mortgageValue:75,
            qtyOwned:0,
            owner:0
        },
        {
            boardId:28,
            propertyType: 'Utility',
            propertyName: 'Water Works',
            propertyImage:'waterworks',
            mortgageValue:75,
            qtyOwned:0,
            owner:0
        },
        {
            boardId:5,
            propertyType: 'Railroad',
            propertyName: 'Reading Railroad',
            propertyImage:'railroad',
            mortgageValue:100,
            baseRent:25,
            qtyOwned:0,
            owner:0
        },
        {
            boardId:15,
            propertyType: 'Railroad',
            propertyName: 'Pennsylvania Railroad',
            propertyImage:'railroad',
            mortgageValue:100,
            baseRent:25,
            qtyOwned:0,
            owner:0
        },
        {
            boardId:25,
            propertyType: 'Railroad',
            propertyName: 'B & O Railroad',
            propertyImage:'railroad',
            mortgageValue:100,
            baseRent:25,
            qtyOwned:0,
            owner:0
        },
        {
            boardId:35,
            propertyType: 'Railroad',
            propertyName: 'Short Line',
            propertyImage:'railroad',
            mortgageValue:100,
            baseRent:25,
            qtyOwned:0,
            owner:0
        },
    ],
    CurrentRoll:0
});

const getters = {
    BoardSpaces:state => state.BoardSpaces,
    Properties:state => state.Properties,
    CurrentRoll:state => state.CurrentRoll
}
const mutations = {
    updateState(state, payload){
        //alert('update boardData - ' + JSON.stringify(payload))
        state[payload.field] = payload.value
    }
}
const actions = {
    set({commit}, payload){
        commit('updateState', {field: payload.field, value: payload.value})
    },
    setPropertyAttr({commit, state}, payload){
        //console.log('payload - ' + JSON.stringify(payload));
        let propertySet = state.Properties;
        
        //console.log('test- target - ' + propertySet[propertySet.findIndex(x=>x.boardId == payload.boardId)]);
        propertySet[propertySet.findIndex(x=>x.boardId == payload.boardId)][payload.attr] = payload.value;
        //console.log('test-afterchange - propertySet target - ' + JSON.stringify(propertySet));
        commit('updateState', {field: 'Properties', value: propertySet});

    }
}

export default{
    namespaced: true,
    state,
    getters,
    mutations,
    actions
}